variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE

before_script:
  - whoami
  - docker info

build:
  stage: build
  tags: [docker-builder]
  script:
    - docker build -t $DOCKER_IMAGE:local_build .

deploy:branch:
  stage: deploy
  tags: [docker-builder]
  except: [tags]
  variables:
    GIT_STRATEGY: none
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker tag $DOCKER_IMAGE:local_build $DOCKER_IMAGE:$CI_COMMIT_REF_NAME
    - docker push $DOCKER_IMAGE:$CI_COMMIT_REF_NAME

deploy:tag:
  stage: deploy
  tags: [docker-builder]
  only: [tags]
  variables:
    GIT_STRATEGY: none
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker tag $DOCKER_IMAGE:local_build $DOCKER_IMAGE:$CI_COMMIT_TAG
    - docker push $DOCKER_IMAGE:$CI_COMMIT_TAG

deploy:latest:
  stage: deploy
  tags: [docker-builder]
  variables:
    GIT_STRATEGY: none
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker tag $DOCKER_IMAGE:local_build $DOCKER_IMAGE:latest
    - docker push $DOCKER_IMAGE:latest
